package kz.bee.drools.planner.schedule.solver;
    dialect "java"

import org.drools.planner.core.score.buildin.hardandsoft.HardAndSoftScoreHolder;
import org.drools.planner.core.score.constraint.IntConstraintOccurrence;
import org.drools.planner.core.score.constraint.ConstraintType;

import kz.bee.drools.planner.schedule.domain.Lesson;
import kz.bee.drools.planner.schedule.domain.UnavailablePeriodConstraint;

global HardAndSoftScoreHolder scoreHolder;

// ############################################################################
// Hard constraints
// ############################################################################
/*
//#
// Two lessons in the same room at the same period.
//#
rule "twoLessonSameTimeSameRoom"
	when
		$lesson1 : Lesson($id : id, $period : period, $room : room)
		$lesson2 : Lesson(id != $id, period == $period, room == $room)
	then
		insertLogical(new IntConstraintOccurrence("twoLessonSameTimeSameRoom", 
							ConstraintType.NEGATIVE_HARD, 1,
							$lesson1, $lesson2));
end
*/
/*//#
// Two classes in the same room at the same period.
//#
rule "twoClassSameTimeSameRoom"
	when
		$lesson1 : Lesson($id : id, $period : period, $room : room, $clazz : course.clazz)
		$lesson2 : Lesson(id != $id, period == $period, room == $room, course.clazz != $clazz)
	then
		insertLogical(new IntConstraintOccurrence("twoClassSameTimeSameRoom",
							ConstraintType.NEGATIVE_HARD, 1, 
							$lesson1, $lesson2));
end
*/

//#
// A different classes(two wx_group child classes) in the same period with different lessons.
//#
rule "wxGroupChildClassesInSamePeriodWithDiffLessons"
	when
		$lesson1 : Lesson($id : id, $period : period, $wxGroupName : course.clazz.wxGroupName, $clazz : course.clazz, $courseName : course.name ) 
		$lesson2 : Lesson(id != $id, period == $period, course.clazz.wxGroupName == $wxGroupName, course.clazz != $clazz, course.name != $courseName ) 
	then
		insertLogical(new IntConstraintOccurrence("wxGroupChildClassesInSamePeriodWithDiffLessons", 
							ConstraintType.NEGATIVE_HARD, 1,
							$lesson1, $lesson2));
end

//#
// A same class(wx_group and all its child classes) in the same period with diffrent lessons.
//#
rule "wxGroupChildClassInSamePeriodWithDiffLessons"
	when
		$lesson1 : Lesson($id : id, $period : period, $wxGroupName : course.clazz.wxGroupName, $clazz : course.clazz, $courseName : course.name ) 
		$lesson2 : Lesson(id != $id, period == $period, course.clazz.wxGroupName == $wxGroupName, course.clazz == $clazz, course.name != $courseName ) 
	then
		insertLogical(new IntConstraintOccurrence("wxGroupChildClassInSamePeriodWithDiffLessons", 
							ConstraintType.NEGATIVE_HARD, 1,
							$lesson1, $lesson2));
end

//#
// Lessons with a same class in the same period.
//#
rule "lessonsWithSameClassInSamePeriod"
	when
		$lesson1 : Lesson($id : id, $period : period, $clazz : course.clazz ) 
		$lesson2 : Lesson(id != $id, period == $period, course.clazz == $clazz ) 
	then
		insertLogical(new IntConstraintOccurrence("lessonsWithSameClassInSamePeriod", 
							ConstraintType.NEGATIVE_HARD, 1,
							$lesson1, $lesson2));
end


//#
// Repeated lessons in the same day(day is the attribute of the Period).
//#
rule "repeatedLessonsInSameDay"
	when
		$lesson1 : Lesson($id : id, period != null, $period : period, $course : course ) 
		$lesson2 : Lesson(id != $id, period != null, period.day == $period.day, course == $course )
	then
		insertLogical(new IntConstraintOccurrence("repeatedLessonsInSameDay", 
							ConstraintType.NEGATIVE_HARD, 2,
							$lesson1, $lesson2));
end


//#
// Collecting lessons of divided classes to a same period
//#
rule "dividedClassLessonsInSamePeriod"
	when
		$lesson : Lesson($id : id, $period : period, $clazz : course.clazz)
        $lessonCount : Number(intValue > 1) from accumulate(
            $lesson2 : Lesson(id != $id, period == $period, course.clazz == $clazz)
            count($lesson2)
        )
	then
		insertLogical(new IntConstraintOccurrence("dividedClassLessonsInSamePeriod", 
							ConstraintType.NEGATIVE_HARD, 2,
							$lesson, $lessonCount));
end

//#
// Lessons with a same teacher in the same period.
//#
rule "lessonsWithSameTeacherInSamePeriod"
	when
		$lesson1 : Lesson($id : id, $period : period, $teacher : course.teacher)
		$lesson2 : Lesson(id != $id, period == $period, course.teacher == $teacher)
	then
		insertLogical(new IntConstraintOccurrence("lessonsWithSameTeacherInSamePeriod",
							ConstraintType.NEGATIVE_HARD, 1, 
							$lesson1, $lesson2));
end
/*
// Availabilities: Each lesson in a period unavailable for that course.
/*rule "unavailablePeriodConstraint"
    when
        $unavailablePeriodConstraint : UnavailablePeriodConstraint($course : course, $period : period)
        $lesson : Lesson(course == $course, period == $period)
    then
    	insertLogical(new IntConstraintOccurrence("twoLessonSameTimeSameTeacher",
    						ConstraintType.NEGATIVE_HARD, 10, 
    						$unavailablePeriodConstraint, $lesson));
end
*/
// ############################################################################
// Soft constraints
// ############################################################################



// ############################################################################
// Calculate score
// ############################################################################

// Accumulate hard constraints
rule "hardConstraintsBroken"
        salience -1 // Do the other rules first (optional, for performance)
    when
        $hardTotal : Number() from accumulate(
            IntConstraintOccurrence(constraintType == ConstraintType.NEGATIVE_HARD, $weight : weight),
            sum($weight) // Vote for http://jira.jboss.com/jira/browse/JBRULES-1075
        )
    then
        scoreHolder.setHardConstraintsBroken($hardTotal.intValue());
end

// Accumulate soft constraints
rule "softConstraintsBroken"
        salience -1 // Do the other rules first (optional, for performance)
    when
        $softTotal : Number() from accumulate(
            IntConstraintOccurrence(constraintType == ConstraintType.NEGATIVE_SOFT, $weight : weight),
            sum($weight) // Vote for http://jira.jboss.com/jira/browse/JBRULES-1075
        )
    then
        scoreHolder.setSoftConstraintsBroken($softTotal.intValue());
end
